# -*- coding: utf-8 -*-
# @Time : 2021/2/10 11:30
# @Author : zhangyawei
# @Email : zhangyawei209@163.com
# @File : second.py
# @Software: PyCharm
# Generated by Selenium IDE
import pytest
import time
from selenium import webdriver
from selenium.webdriver.common.by import By

class TestDemo():
    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.driver.implicitly_wait(5)#隐式等待每隔0.5秒回去查询页面元素

    def teardown_method(self, method):
        self.driver.quit()

    def test_demo(self):
        self.driver.get("https://ceshiren.com/")
        self.driver.set_window_size(1280, 719)
        self.driver.find_element(By.LINK_TEXT, "所有分类").click()
        time.sleep(1)
        element = self.driver.find_element(By.LINK_TEXT, "所有分类")
        result = element.get_attribute('class')     #判断这个元素的class是否等于'active'
        assert 'active' == result

